name: Mark it done CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

jobs:
  run_script:
    name: Run python script
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the script
        env:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
        run: |
          ls -l
          python3 mark-it-done.py
